coordinator:
  service:
    type: NodePort
    nodePort: 30005
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  config:
    config.properties: |
      coordinator=true
      node-scheduler.include-coordinator=true
      http-server.http.port=8080
      discovery-server.enabled=true
      discovery.uri=http://trino-coordinator.trino.svc.cluster.local:8080
    jvm.config: |
      -server
      -Xmx2G
      -XX:+ExitOnOutOfMemoryError
    node.properties: |
      node.environment=production
      node.id=trino-coordinator
      node.data-dir=/data/trino

workers:
  count: 1
  resources:
    requests:
      cpu: "1"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"

catalogs:
  lakehouse: |
    connector.name=iceberg
    iceberg.catalog.type=nessie
    iceberg.nessie-catalog.uri=http://nessie.nessie-ns.svc.cluster.local:19120/api/v1
    iceberg.nessie-catalog.ref=main
    iceberg.nessie-catalog.default-warehouse-dir=s3://warehouse
    iceberg.file-format=PARQUET

    fs.native-s3.enabled=true
    s3.endpoint=http://minio.minio.svc.cluster.local:9000
    s3.aws-access-key=minioadmin
    s3.aws-secret-key=minioadmin123
    s3.path-style-access=true
    s3.region=us-east-2
