kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # MinIO S3 API
        hostPort: 30000
      - containerPort: 30001  # MinIO Console
        hostPort: 30001
      - containerPort: 30002  # Airbyte Web UI
        hostPort: 30002
      - containerPort: 30003  # Airflow Web UI 
        hostPort: 30003
      - containerPort: 30004  # StarRocks FE Web UI (8030)
        hostPort: 30004
      - containerPort: 30005  # StarRocks BE Web UI (8040)
        hostPort: 30005
      - containerPort: 30006  # StarRocks CN Web UI (8060)
        hostPort: 30006
      - containerPort: 30007  # StarRocks FE Proxy (9010)
        hostPort: 30007
      - containerPort: 30008  # StarRocks FE HTTP API / REST interface (9010)
        hostPort: 30008
      - containerPort: 30009 # Nessie Web UI
        hostPort: 30009
