kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000  # MinIO S3 API
        hostPort: 30000
      - containerPort: 30001  # MinIO Console
        hostPort: 30001
      - containerPort: 30002  # Airbyte Web UI
        hostPort: 30002
      - containerPort: 30003  # Airflow Web UI 
        hostPort: 30003
      - containerPort: 30004 # Nessie Web UI
        hostPort: 30004
      - containerPort: 30005 # Trino Web UI
        hostPort: 30005
